services:
  api_auth:
    image: labcapital/apps:Auth
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - github_token_commons

secrets:
  github_token_commons:
    environment: GITHUB_TOKEN_COMMONS
