services:
  api_auth:
    image: labcapital/apps:Auth
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - github_token

secrets:
  github_token:
    environment: GITHUB_TOKEN 
