name: Release commons to GH

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Zip shared directories
        run: |
          (cd packages/shared_db && zip -r ../../shared_db.zip .)
          (cd packages/shared_models && zip -r ../../shared_models.zip .)
          (cd packages/shared_schemas && zip -r ../../shared_schemas.zip .)
          (cd packages/shared_utils && zip -r ../../shared_utils.zip .)

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            shared_db.zip
            shared_models.zip
            shared_schemas.zip
            shared_utils.zip
            packages/shared_utils/fetcher.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}